webtalk_init -webtalk_dir /home/butvinm/Dev/ITMO/soc/lab1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/dev_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 16 16:57:36 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "655205dd-2893-405e-ac2e-9f09e27508e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fc2989951a734bbeb61cd4b2a0eabffa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1260P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2281.307 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "41.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "730035 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "22.42_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "130548_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3217873926 -regid "" -xml /home/butvinm/Dev/ITMO/soc/lab1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/dev_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/butvinm/Dev/ITMO/soc/lab1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/dev_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/butvinm/Dev/ITMO/soc/lab1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/dev_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
